[package]
name = "memmem-delimiter-codec"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "arbitrary-length delimiter codec for tokio using memchr"
readme = "README.md"
repository = "https://github.com/wobcom/memmem-delimiter-codec"
keywords = [ "codec", "delimiter", "memmem", "tokio" ]
categories = [ "encoding" ]

[dependencies]
memchr = "2.8.3"
tokio-util = { version = "0.7.19", features = ["codec"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
tokio-stream = "0.1.19"
tokio-test = "0.4.5"
